NodeJS task-3 done
MD-Liyaqath-Ali/HomeTask pull request #12
Opened 2022-06-20 11:33 UTC by MD-Liyaqath-Ali

2022-06-22 13:00 UTC, leenabodhe requested changes
Please add missing files

2022-06-22 13:00 UTC, leenabodhe commented on NodeJS-task-3/app.js
> +const router = require("./routes/routers.js").router;
router folder is not present

2022-06-23 09:14 UTC, MD-Liyaqath-Ali commented on NodeJS-task-3/controllers/userControllers.js
> +        let record = await userService.saveUserInDB(id, login, age, password, isdeleted);
Changes made

2022-06-23 09:14 UTC, MD-Liyaqath-Ali commented on NodeJS-task-3/app.js
> +const router = require("./routes/routers.js").router;
Changes made

2022-07-07 08:08 UTC, merged